apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # Replace these with your base64 encoded values
  # Run: echo -n "your-value" | base64
  mysql-host: cHJvZHVjdC1teXNxbC1yc3IyLm15c3FsLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  mysql-user: c3FsYWRtaW4=
  mysql-password: U2h5QG0xMzEy
  mysql-db: cHJvZHVjdGRi
