# MySQL Database Connection
spring.datasource.url=jdbc:mysql://product-mysql-rsr2.mysql.database.azure.com:3306/productdb?useSSL=true&requireSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=sqladmin
spring.datasource.password=Shy@m1312
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server
server.port=8080